### PR TITLE
Include boost/system/system_error.hpp

### PR DESCRIPTION
**Pull request by benjaminbollen**

### CODE REVIEW

**Comment by inetic** [comment]
Hi Ben, did you get an error on a particular platform/gcc version/boost version about this not being included?

**Comment by benjaminbollen** [comment]
Yes, gcc release on 'some machines'

**Comment by benjaminbollen** [comment]
QA, Ross was still testing it :)

**Comment by inetic** [comment]
Arrr, new to this, sorry.

**Pull request merged**
